SELECT DISTINCT
       A.AUTHOR_ID,
       A.AUTHOR_NAME,
       B.CATEGORY,
       (SELECT SUM(BS.SALES* BB.PRICE) 
       FROM BOOK BB 
       JOIN BOOK_SALES BS ON BB.BOOK_ID = BS.BOOK_ID
       WHERE BS.SALES_DATE LIKE '2022-01%' AND A.AUTHOR_ID = BB.AUTHOR_ID AND B.CATEGORY = BB.CATEGORY) 
       AS TOTAL_SALES
          
FROM BOOK B JOIN AUTHOR A USING(AUTHOR_ID)
ORDER BY A.AUTHOR_ID , B.CATEGORY DESC