SELECT ANIMAL_ID, 
       ANIMAL_TYPE,
       NAME
       
FROM ANIMAL_INS I 
  JOIN ANIMAL_OUTS O USING (ANIMAL_ID, ANIMAL_TYPE, NAME)

WHERE I.SEX_UPON_INTAKE LIKE 'Intact%'
  AND O.SEX_UPON_OUTCOME NOT LIKE 'Intact%'