SELECT *
FROM(SELECT I.REST_ID,
       I.REST_NAME,
       I.FOOD_TYPE,
       I.FAVORITES,
       I.ADDRESS,
       (SELECT ROUND(AVG(R.REVIEW_SCORE),2)
        FROM REST_REVIEW R
        WHERE I.REST_ID = R.REST_ID 
       )AS SCORE
       FROM REST_INFO I
       WHERE I.ADDRESS LIKE '서울%'
    ) AS SUB

WHERE SUB.SCORE IS NOT NULL
ORDER BY SUB.SCORE DESC, SUB.FAVORITES DESC