SELECT 
    DATE_FORMAT(SALES_DATE, '%Y') AS YEAR,
    DATE_FORMAT(SALES_DATE, '%m') AS MONTH,
    GENDER,
    COUNT(DISTINCT USER_ID) AS USERS
       
FROM USER_INFO 
JOIN ONLINE_SALE 
USING (USER_ID)

WHERE GENDER IS NOT NULL

GROUP BY DATE_FORMAT(SALES_DATE, '%Y'), DATE_FORMAT(SALES_DATE, '%m'), GENDER
ORDER BY DATE_FORMAT(SALES_DATE, '%Y'), DATE_FORMAT(SALES_DATE, '%m'), GENDER