SELECT FLAVOR
FROM( SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER FROM FIRST_HALF
      UNION ALL 
      SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER FROM JULY
) AS PRODUCT

GROUP BY FLAVOR 
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3
OFFSET 0