SELECT SUM(G.SCORE) AS SCORE,
       G.EMP_NO,
       E.EMP_NAME,
       E.POSITION,
       E.EMAIL
       
FROM HR_GRADE G JOIN HR_EMPLOYEES E USING(EMP_NO)
WHERE YEAR = '2022'
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
OFFSET 0