SELECT CATEGORY,
       SUM(SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S USING(BOOK_ID)
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY


# SELECT * FROM BOOK JOIN BOOK_SALES USING(BOOK_ID)