SELECT CATEGORY,
       PRICE AS MAX_PRICE,
       PRODUCT_NAME
       
FROM FOOD_PRODUCT FP

WHERE FP.PRICE = (SELECT MAX(PRICE)
       FROM FOOD_PRODUCT SUB
       WHERE CATEGORY IN ('과자','국', '김치', '식용유')
         AND FP.CATEGORY = SUB.CATEGORY
      )

ORDER BY MAX_PRICE DESC